version: '3.7' 

services:
  web:
    container_name: flask_sqlalchemy
    build: 
      context: .
    # Useful for debugging
    # entrypoint: ["sh", "-c", "sleep 2073600"]
    ports:
      - "5000:5000"
    volumes:
      - ./:/code
    environment: 
      - FLASK_ENV=$FLASK_ENV
    depends_on:
      - database   
  
  database:
    container_name: postgres_sqlalchemy
    image: postgres:latest
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - runner_app_vol:/var/lib/postgresql/data
  
volumes:
  runner_app_vol:
  
  
  